spring.application.name=Backend

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/kala_kriti_db
spring.datasource.username=
spring.datasource.password=

# Optional for PostgresDB
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
